INSERT INTO TOPICS (title, description, userEmail)
VALUES 
    ('Understanding Artificial Intelligence','Explore the field of AI, including machine learning, neural networks, and natural language processing','amaryllis@leicester.ac.uk'),
    ('Unlocking Insights with Data Science',' Learn how data analysis and statistical techniques drive decision-making in various domains','amaryllis@leicester.ac.uk'),
    ('Demystifying Blockchain','Delve into the world of blockchain, decentralized ledgers, and their applications in finance and beyond','amaryllis@leicester.ac.uk'),
    ('Securing the Digital Worlde','Discover methods to protect digital information, networks, and systems from cyber threats','amaryllis@leicester.ac.uk'),
    ('Connecting the IoT','Explore the concept of interconnected devices and their impact on our daily lives and industries.','atlas@leicester.ac.uk'),
    ('Navigating Cloud Computing','Understand how cloud services work, their benefits, and their role in modern IT infrastructure.','atlas@leicester.ac.uk'),
    ('Entering the Quantum Realm','Learn about the principles of quantum computing and its potential to revolutionize computation','atlas@leicester.ac.uk'),
    ('Building Intelligent Machines','Dive into machine learning algorithms, supervised and unsupervised learning, and real-world applications','caius@leicester.ac.uk'),
    ('The Power of NLP','Explore how computers understand and generate human language, enabling chatbots and language translation.','caius@leicester.ac.uk'),
    ('Seeing with Computers','Discover computer vision techniques for image and video processing, object recognition, and more.','caius@leicester.ac.uk'),
    ('Crafting the Web','Learn about front-end and back-end development, creating websites and web applications.','caius@leicester.ac.uk'),
    ('Mastering Software Development','Explore the software development life cycle, design patterns, and best practices.','elowen@leicester.ac.uk'),
    ('Building Mobile Experiences','Learn to develop mobile apps for iOS and Android platforms, including user interface design.','elowen@leicester.ac.uk'),
    ('Designing User-Friendly Interfaces','Understand the principles of HCI to create intuitive and user-centered software interfaces.','elowen@leicester.ac.uk'),
    ('The Art of Algorithms','Study algorithmic problem-solving and the efficiency of algorithms in different scenarios.','elowen@leicester.ac.uk'),
    ('Managing Computer Resources','Explore the design and functionality of operating systems, including memory management and multitasking.','lucian@leicester.ac.uk'),
    ('Organizing Data Efficiently','Learn about relational databases, SQL, and data management techniques.','lucian@leicester.ac.uk'),
    ('Connecting the World','Understand networking protocols, data transmission, and network security.','lucian@leicester.ac.uk'),
    ('Visualizing Digital Worlds','Explore the creation of 2D and 3D graphics, animation, and interactive visualizations.','lucian@leicester.ac.uk'),
    ('The Science of Secrecy','Study encryption techniques, secure communication, and cryptographic protocols.','orion@leicester.ac.uk'),
    ('Translating Code','Learn how compilers convert high-level programming languages into machine code.','orion@leicester.ac.uk'),
    ('Scaling and Distribution',' Explore the challenges and benefits of distributed computing and networking.','orion@leicester.ac.uk'),
    ('Quality Assurance in Software','Discover testing methodologies, test automation, and ensuring software reliability.','orion@leicester.ac.uk'),
    ('Blueprint of Computers','Understand the design and organization of computer hardware components.','selene@leicester.ac.uk'),
    ('Building Brain-Inspired Models','Study the structure and operation of artificial neural networks in machine learning.','selene@leicester.ac.uk'),
    ('Interpreting Human Language','Dive into advanced NLP techniques for language understanding and sentiment analysis','selene@leicester.ac.uk'),
    ('The World of Robots',' Explore robotic systems, kinematics, control, and applications in automation.','selene@leicester.ac.uk'),
    ('White Hat Adventures','Learn about ethical hacking, penetration testing, and cybersecurity from an offensive perspective.','thalia@leicester.ac.uk'),
    ('Unearthing Hidden Patterns','Discover techniques for extracting valuable patterns and insights from large datasets.','thalia@leicester.ac.uk'),
    ('Computing in Paralle','Explore parallel programming, multi-core processors, and parallel algorithm design.','thalia@leicester.ac.uk'),
    ('Pursuing Human-Level AI','Delve into the concept of AGI, its challenges, and its potential impact on society.','thalia@leicester.ac.uk'),
    ('Deep Dive into Deep Learning','Study deep neural networks, convolutional networks, and deep learning applications.','thalia@leicester.ac.uk'),
    ('Defending the Web','Learn about web application security, common vulnerabilities, and secure coding practices.','thalia@leicester.ac.uk'),
    ('Choosing the Right Approach','Explore agile, waterfall, and other software development methodologies','zephyrine@leicester.ac.uk'),
    ('Creating Interactive Experiences','Study fuzzy logic, which deals with imprecision and uncertainty in data.','zephyrine@leicester.ac.uk'),
    ('Computing in the Life Sciences',' Explore the use of computational methods in biology, bioinformatics, and genomics.','zephyrine@leicester.ac.uk'),
    ('Visualizing Data Insights','Learn about effective data visualization techniques for conveying information.','zephyrine@leicester.ac.uk'),
    ('Embedded Computing','Understand the design of embedded systems for specific applications, such as IoT devices and robotics.s','zephyrine@leicester.ac.uk');
    